import type { Metadata } from "next";
import { Schibsted_Grotesk, Martian_Mono, Geist } from "next/font/google";
import "./globals.css"
import LightRays from "../components/LightRays"
import NavBar from "@/components/NavBar";

const schibstedGrotesk = Schibsted_Grotesk({
  variable: "--font-schibsted_grotesk",
  subsets: ["latin"],
});

const martianMono = Martian_Mono({
  variable: "--font-martian_mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZEvent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
    lang="en"
    className={`${schibstedGrotesk.variable} ${martianMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar />  
        <div className="absolute z-[-1] inset-0 top-0 min-h-screen w-full">
          <LightRays
          raysOrigin="top-center-offset"
          raysColor="#5dfeca"
          raysSpeed={1}
          lightSpread={1.5}
          rayLength={2}
          followMouse={true}
          mouseInfluence={0.02}
          noiseAmount={0}
          distortion={0.06}
          pulsating={false}
          fadeDistance={5}
          saturation={1}
          />
        </div>

        <main>
          {children}
        </main>

      </body>
    </html>
  );
}
